use_frameworks!

platform :ios, '10.0'

target 'Abds1_Example' do
  pod 'Abds1', :path => '../'

  target 'Abds1_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
    pod 'Alamofire'
  end
end
